### PR TITLE
Update com.spotify/docker-client to 8.1.1

### PR DESCRIPTION
**Pull request by soleger**

### CODE REVIEW

**Comment by RangerRick** [comment]
I assume you've run some tests using the updated version and it doesn't break anything?  Can't really test it with bamboo in this case...

**Comment by soleger** [comment]
Let me try running the full set of smoke tests on my system.

**Comment by soleger** [comment]
All smoke tests run properly on my Mac (Docker 17.03.0-ce-mac2). That might be a little newer than the Bamboo machines but they IT docker-client back to docker 1.8 afaik.

**Comment by RangerRick** [comment]
good enough for me :)

**Pull request merged**
